import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { startBrowserFixture } from './browser_fixture_server.mjs';
const { chromium } = await import(process.env.SURGE_RELAY_PLAYWRIGHT_MODULE || 'playwright');
const fixture = await startBrowserFixture();
fixture.setDualTarget('module-0');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = { timestamp: new Date().toISOString(), browser: browser.version(), fixtureOnly: true, checks: [], pageErrors: [] };
try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  page.on('pageerror', error => report.pageErrors.push(error.message));
  await page.route('**/*', route => new URL(route.request().url()).origin === fixture.origin ? route.continue() : route.abort());
  await page.goto(fixture.origin);
  await page.locator('[data-action="publish-selected"]').click();
  await page.locator('[data-publish-module="module-0"]').check();
  await page.locator('[data-operation="preview-selected"]').click();
  await page.locator('[data-operation="execute-publish"]').waitFor();
  assert.match(await page.locator('#operation-content').textContent(), /Fixture.sgmodule:3/);
  assert.match(await page.locator('[data-operation="execute-publish"]').textContent(), /确认并继续发布/);
  assert.equal(fixture.requests.filter(request => request.path === '/api/publish').length, 0);
  await page.locator('[data-operation="execute-publish"]').click();
  await page.locator('#confirm-cancel').click();
  assert.equal(fixture.requests.filter(request => request.path === '/api/publish').length, 0);
  await page.locator('[data-operation="execute-publish"]').click();
  assert.equal(await page.locator('#confirm-accept').textContent(), '继续发布');
  await page.locator('#confirm-accept').click();
  await page.locator('[data-operation="retry-publish"]').waitFor();
  assert.match(await page.locator('#operation-content').textContent(), /本地 · 成功/);
  assert.match(await page.locator('#operation-content').textContent(), /GitHub · 失败/);
  await page.locator('[data-operation="retry-publish"]').click();
  await page.locator('[data-operation="execute-publish"]').waitFor();
  assert.deepEqual(await page.locator('.operation-target h3').allTextContents(), ['GitHub']);
  await page.locator('[data-operation="execute-publish"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('GitHub · 成功'));
  report.checks.push('Selected publication preview has no writes; cancel has no writes; partial result only retries failed GitHub target');
  await page.locator('#operation-close').click();
  await page.reload();
  await page.locator('[data-action="publish-results"]').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('GitHub · 成功'));
  report.checks.push('Prior selected publication result is recoverable after reload');
  await page.locator('#operation-close').click();
  await page.locator('[data-action="publish-github"]').click();
  await page.locator('[data-operation="execute-publish"]').waitFor();
  assert.match(await page.locator('#operation-content').textContent(), /Obsolete.sgmodule/);
  fixture.invalidateTickets();
  await page.locator('[data-operation="execute-publish"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('内容或配置已变化'));
  assert.equal(await page.locator('[data-operation="execute-publish"]').count(), 0);
  report.checks.push('GitHub full preview displays deletions; stale publication ticket requires a new preview');
  await page.locator('#operation-close').click();
  await page.locator('.module-open').first().click();
  await page.locator('[data-action="compare-sync"]').click();
  await page.locator('[data-operation="local-to-github"]').waitFor();
  assert.equal(await page.locator('.diff-removed').count(), 1);
  assert.equal(await page.locator('.diff-added').count(), 1);
  await page.locator('[data-operation="local-to-github"]').click();
  await page.locator('#confirm-cancel').click();
  assert.equal(fixture.requests.filter(request => request.path.endsWith('/sync-conflict')).length, 0);
  fixture.invalidateTickets();
  await page.locator('[data-operation="local-to-github"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('内容或配置已变化'));
  await page.locator('[data-operation="refresh-sync"]').click();
  await page.locator('[data-operation="github-to-local"]').waitFor();
  await page.locator('[data-operation="github-to-local"]').click();
  assert.match(await page.locator('#confirm-title').textContent(), /用 GitHub 覆盖本地/);
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('Fixture synchronization complete'));
  assert.equal(fixture.requests.filter(request => request.path.endsWith('/sync-conflict')).at(-1).payload.direction, 'gitHubToLocal');
  report.checks.push('Two-sided diff, directional cancel, stale sync rejection and refreshed direction confirmation all work');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-operation="refresh-sync"]').click();
  await page.locator('[data-operation="local-to-github"]').waitFor();
  assert.equal(await page.locator('[data-operation="local-to-github"]').isDisabled(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  report.checks.push('Mobile sync dialog has no page overflow; identical sides disable destructive actions');
  await page.locator('#operation-close').click();
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.locator('[data-action="tab-preview"]').click();
  await page.waitForFunction(() => !document.querySelector('#code-editor').disabled);
  await page.locator('#code-editor').fill('unsaved restore draft');
  fixture.setContent('module-0', 'concurrent restore version');
  await page.locator('[data-action="restore-preview"]').click();
  await page.locator('#confirm-accept').click();
  await page.locator('[data-action="compare-preview"]').waitFor({ state: 'visible' });
  assert.equal(fixture.content('module-0'), 'concurrent restore version');
  assert.equal(await page.locator('#code-editor').inputValue(), 'unsaved restore draft');
  await page.locator('[data-action="restore-preview"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#preview-status').textContent === '已保存');
  assert.match(await page.locator('#code-editor').inputValue(), /#!name=Browser fixture/);
  report.checks.push('Conditional conversion restore rejects stale ETag, retains draft, then restores only after new confirmation');
  await page.locator('#code-editor').fill('history draft to keep');
  await page.evaluate(() => previewController.flushDrafts());
  await page.locator('[data-action="tab-info"]').click();
  await page.locator('[data-action="version-history"]').click();
  await page.locator('[data-operation="compare-version"]').click();
  await page.locator('[data-operation="restore-version"]').waitFor();
  assert.match(await page.locator('#operation-content').textContent(), /历史版本 → 当前缓存/);
  assert.match(await page.locator('#operation-content').textContent(), /scripts\/historical.js/);
  const publicationCount = fixture.requests.filter(request => request.path === '/api/publish').length;
  await page.locator('[data-operation="restore-version"]').click();
  assert.match(await page.locator('#confirm-message').textContent(), /本次仅恢复缓存并暂停该模块自动刷新，不立即发布/);
  await page.locator('#confirm-cancel').click();
  assert.equal(fixture.requests.filter(request => request.path.endsWith('/versions/fixture-history-1/restore')).length, 0);
  fixture.invalidateTickets();
  await page.locator('[data-operation="restore-version"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('当前缓存或历史版本已变化'));
  assert.equal(await page.locator('[data-operation="restore-version"]').count(), 0);
  await page.locator('[data-operation="refresh-version"]').click();
  await page.locator('[data-operation="restore-version"]').click();
  await page.locator('#confirm-accept').click();
  await page.waitForFunction(() => document.querySelector('#operation-content').textContent.includes('未立即发布'));
  assert.match(fixture.content('module-0'), /Historical fixture/);
  assert.equal(fixture.requests.filter(request => request.path === '/api/publish').length, publicationCount);
  await page.locator('#operation-close').click();
  await page.locator('[data-action="tab-preview"]').click();
  await page.waitForFunction(() => document.querySelector('#code-editor').value === 'history draft to keep');
  assert.match(await page.locator('#preview-message').textContent(), /服务器内容已变化/);
  report.checks.push('Version history diff and assets, cancelled restore, stale ticket recompare, cache-only rollback and unsaved browser draft preservation');
  await page.setViewportSize({ width: 820, height: 900 });
  await page.locator('[data-action="tab-info"]').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  report.checks.push('Version-history and publication actions wrap without overflow at 820 px desktop width');
  assert.deepEqual(report.pageErrors, []);
  await context.close();
} catch (error) { report.failure = error.message.slice(0, 3000); process.exitCode = 1; }
finally {
  await browser.close(); await fixture.close();
  await mkdir('docs/performance', { recursive: true });
  await writeFile('docs/performance/web-publication-acceptance.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
}
