import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { startBrowserFixture } from './browser_fixture_server.mjs';
const { chromium } = await import(process.env.SURGE_RELAY_PLAYWRIGHT_MODULE || 'playwright');
const fixture = await startBrowserFixture();
fixture.setCount(100);
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = { timestamp: new Date().toISOString(), browser: browser.version(), headless: true, viewport: { width: 390, height: 844 }, fixtureOnly: true, checks: [], pageErrors: [] };
try {
  const context = await browser.newContext({ viewport: report.viewport });
  const page = await context.newPage();
  page.on('pageerror', error => report.pageErrors.push(error.message));
  await page.route('**/*', route => new URL(route.request().url()).origin === fixture.origin ? route.continue() : route.abort());
  await page.goto(fixture.origin);
  const rows = page.locator('.module-open');
  await rows.first().waitFor();
  const selected = rows.nth(40);
  await selected.scrollIntoViewIfNeeded();
  const moduleID = await selected.evaluate(element => element.closest('.module-row').dataset.id);
  const listScroll = await page.evaluate(() => scrollY);
  assert.ok(listScroll > 0);
  await selected.click();
  await page.waitForFunction(() => document.body.classList.contains('has-selection'));
  assert.equal(new URL(page.url()).searchParams.get('module'), moduleID);
  assert.equal(await page.locator('#detail').evaluate(element => element.contains(document.activeElement)), true);
  await page.locator('#detail-tab-info').focus();
  await page.keyboard.press('ArrowRight');
  await page.locator('#code-editor').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#detail-tab-preview').evaluate(element => element === document.activeElement), true);
  await page.keyboard.press('Home');
  assert.equal(await page.locator('#detail-tab-info').evaluate(element => element === document.activeElement), true);
  report.checks.push('Mobile detail entry selects URL target and visible detail focus; actual ArrowRight/Home keys switch tabs and focus');
  await page.locator('[data-action="edit"]').click();
  await page.locator('#module-dialog').waitFor({ state: 'visible' });
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => !document.querySelector('#module-dialog').open);
  await page.waitForFunction(() => document.activeElement?.matches('[data-action="edit"]'));
  report.checks.push('Escape closes the real edit dialog and returns focus to its opener');
  await page.locator('#mobile-back').click();
  await page.waitForFunction(() => !document.body.classList.contains('has-selection'));
  await page.waitForTimeout(350);
  const back = await page.evaluate(() => ({ url: location.href, history: history.state, scroll: scrollY, focusID: document.activeElement?.closest('.module-row')?.dataset.id, focusTag: document.activeElement?.tagName, focusInert: !!document.activeElement?.closest('[inert]') }));
  report.buttonBack = { moduleID, listScroll, ...back };
  assert.equal(new URL(back.url).searchParams.get('module'), null);
  assert.equal(back.focusID, moduleID, 'returning to the list must restore focus to the opened module');
  assert.equal(back.focusInert, false);
  assert.ok(Math.abs(back.scroll - listScroll) <= 1, 'sidebar scroll must survive mobile return');
  report.checks.push('Mobile back button returns to the list history entry, restores module focus and preserves sidebar scroll');
  await page.locator(`.module-row[data-id="${moduleID}"] .module-open`).click();
  await page.waitForFunction(() => document.body.classList.contains('has-selection'));
  await page.goBack();
  await page.waitForFunction(() => !document.body.classList.contains('has-selection'));
  await page.waitForFunction(id => document.activeElement?.closest('.module-row')?.dataset.id === id, moduleID);
  await page.waitForFunction(y => Math.abs(scrollY - y) <= 1, listScroll);
  assert.ok(Math.abs(await page.evaluate(() => scrollY) - listScroll) <= 1);
  await page.goForward();
  await page.waitForFunction(() => document.body.classList.contains('has-selection'));
  assert.equal(new URL(page.url()).searchParams.get('module'), moduleID);
  assert.equal(await page.locator('#detail').evaluate(element => element.contains(document.activeElement)), true);
  report.checks.push('Browser history back and forward restore list/detail targets with visible focus and retained sidebar scroll');
  await page.keyboard.press('Meta+k');
  await page.waitForFunction(() => !document.body.classList.contains('has-selection') && document.activeElement === document.querySelector('#search-input'));
  await page.waitForTimeout(100);
  assert.equal(await page.locator('#search-input').evaluate(element => element === document.activeElement), true);
  report.checks.push('Command-K from mobile detail keeps focus on search rather than restoring the former module focus');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(report.pageErrors, []);
  await context.close();
} catch (error) { report.failure = error.stack?.slice(0, 3000) || error.message; process.exitCode = 1; }
finally {
  await browser.close(); await fixture.close();
  await mkdir('docs/performance', { recursive: true });
  await writeFile('docs/performance/web-mobile-navigation-acceptance.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
}
