import assert from 'node:assert/strict';
import { indexHTML } from './harness.mjs';

const logicScriptIndex = indexHTML.indexOf('/web-logic.js');
const optionsScriptIndex = indexHTML.indexOf('/web-options.js');
const formatScriptIndex = indexHTML.indexOf('/web-format.js');
const markupScriptIndex = indexHTML.indexOf('/web-markup.js');
const sidebarScriptIndex = indexHTML.indexOf('/web-sidebar.js');
const activityScriptIndex = indexHTML.indexOf('/web-activity.js');
const apiScriptIndex = indexHTML.indexOf('/web-api.js');
const stateScriptIndex = indexHTML.indexOf('/web-state.js');
const editorScriptIndex = indexHTML.indexOf('/web-editor.js');
const feedbackScriptIndex = indexHTML.indexOf('/web-feedback.js');
const previewScriptIndex = indexHTML.indexOf('/web-preview.js');
const appScriptIndex = indexHTML.indexOf('/app.js');
assert.ok(logicScriptIndex >= 0, 'index should load web-logic.js');
assert.ok(optionsScriptIndex > logicScriptIndex, 'web-options.js must load after web-logic.js');
assert.ok(formatScriptIndex > optionsScriptIndex, 'web-format.js must load after web-options.js');
assert.ok(markupScriptIndex > formatScriptIndex, 'web-markup.js must load after web-format.js');
assert.ok(sidebarScriptIndex > markupScriptIndex, 'web-sidebar.js must load after web-markup.js');
assert.ok(activityScriptIndex > sidebarScriptIndex, 'web-activity.js must load after web-sidebar.js');
assert.ok(apiScriptIndex > activityScriptIndex, 'web-api.js must load after web-activity.js');
assert.ok(stateScriptIndex > apiScriptIndex, 'web-state.js must load after web-api.js');
assert.ok(editorScriptIndex > stateScriptIndex, 'web-editor.js must load after web-state.js');
assert.ok(feedbackScriptIndex > editorScriptIndex, 'web-feedback.js must load after web-editor.js');
assert.ok(previewScriptIndex > feedbackScriptIndex, 'web-preview.js must load after web-feedback.js');
assert.ok(appScriptIndex > previewScriptIndex, 'web-preview.js must load before app.js');
assert.match(indexHTML, /name="storageLocation"/);
assert.match(indexHTML, /name="outputFolder"/);
assert.match(indexHTML, /id="output-path-preview"/);
